### ISSUE TITLE
imgAttributes error on exhibit

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/mall-theme#6]
[Tower Tour exhibit](https://omeka-dev-2022.carleton.edu/cgmrdev/exhibits/show/tower-tour) is throwing the following error from the ExhibitBuilder plugin:

Notice: Undefined index: imgAttributes in /var/www/html/cgmrdev/plugins/ExhibitBuilder/views/helpers/ExhibitAttachment.php on line 30

Probably want to figure out what it's looking for that we are missing rather than changing that plugin code we don't control, but might check their issue queue to see if anyone has reported similar.

**Comment by tutingjun** [comment]
The issue is addressed [here](https://github.com/omeka/plugin-ExhibitBuilder/pull/136). I test the code to the pull request and the error message disappear. After testing, I change it back to the way it is. This pull request is relatively new so it is not in the latest release. Do we want to change it? 

Also, I find that the images in the interactive map of [Tower Tour exhibit](https://omeka-dev-2022.carleton.edu/cgmrdev/exhibits/show/tower-tour) have really bad alt-text (just the file name). This is because there is no   Dublin Core for each image. I add a title to the image file for The Torre delle Milizie and the alt text for that image is the title I added. Do we need to add them as the title of the exhibit?

**Comment by tutingjun** [comment]
Change the file `cgmrdev/plugins/ExhibitBuilder/views/helpers/ExhibitAttachment.php` in line 27-33. Close the issue when ExhibitBuilder publishes a new release.

**Comment by apjmason** [comment]
Fixed in Exhibit Builder 3.5.4 release. Closing.
